#nullable enable

using NUnit.Framework;
using TableCore.Core.UI;
using TableCore.Lobby;

namespace TableCore.Tests.Lobby
{
    [TestFixture]
    public class PlayerNamePlaceholderTests
    {
        [TestCase("Player", true)]
        [TestCase("Player 1", true)]
        [TestCase("player 12", true)]
        [TestCase("Player 001", true)]
        [TestCase("Player ", false)]
        [TestCase("Players 1", false)]
        [TestCase("Play 1", false)]
        [TestCase("Alice", false)]
        [TestCase("", false)]
        public void IsAutoGeneratedDisplayName_DetectsDefaultPatterns(string value, bool expected)
        {
            var result = PlayerCustomizationHud.IsAutoGeneratedDisplayName(value);

            Assert.That(result, Is.EqualTo(expected));
        }

        [Test]
        public void ShouldClearPlaceholderOnKey_SkipsEnter()
        {
            var result = PlayerCustomizationHud.ShouldClearPlaceholderOnKey(FloatingKeyboardSpecialKeys.Enter);

            Assert.That(result, Is.False);
        }

        [TestCase("A")]
        [TestCase(" ")]
        [TestCase(FloatingKeyboardSpecialKeys.Backspace)]
        [TestCase(FloatingKeyboardSpecialKeys.Clear)]
        [TestCase(FloatingKeyboardSpecialKeys.Space)]
        public void ShouldClearPlaceholderOnKey_AllowsEditingKeys(string key)
        {
            var result = PlayerCustomizationHud.ShouldClearPlaceholderOnKey(key);

            Assert.That(result, Is.True);
        }
    }
}
